<a href="https://colab.research.google.com/github/oladimejiala/schisto-project/blob/main-schisto/PSAC_Korede_Analysis_and_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
# from sklearn.tree import DecisionTreeClassifier

In [5]:
df = pd.read_csv('/content/drive/MyDrive/koredepsac/psacquant.csv')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Extracting participants biometric data with Schistosoma eggcount for comparison

In [11]:
biometrics = df.iloc[:, 6:8].values
egg_count = df.sheggcnt.values
egg_count
# splitting the dataset into the training and test set
x_train, x_test, y_train, y_test  = train_test_split(biometrics, egg_count, test_size = 0.2, random_state = 0)
biometrics

array([['4', '85'],
       ['8', '103'],
       ['5', '76'],
       ['12', '78'],
       ['14', '90'],
       ['10', '97'],
       ['7', '78'],
       ['9', '99'],
       ['10', '119'],
       ['11', '121'],
       ['6', '88'],
       ['9', '102'],
       ['12', '119'],
       ['9', '110'],
       ['9', '104'],
       ['7', '90'],
       ['13', '125'],
       ['11', '114'],
       ['8', '98'],
       ['8', '86'],
       ['4', '77'],
       ['9', '84'],
       ['9', '98'],
       ['10', '105.5'],
       ['8', '89'],
       ['7', '89'],
       ['8', '117'],
       ['8', '116'],
       ['6', '86'],
       ['6', '80'],
       ['8', '81.5'],
       ['9', '93.5'],
       ['7', '79'],
       ['11', '116'],
       ['11', '110'],
       ['10', '99'],
       ['13', '12'],
       ['14', '113'],
       ['12', '114'],
       ['8', '105'],
       ['5', '89'],
       ['6', '95.5'],
       ['6', '94'],
       ['6.5', '99.5'],
       ['17', '125'],
       ['5', '68.5'],
       ['3', '60'],
       ['7',

Prediction using Decision Tree Regressor

In [1]:
# using decision tree to make sense out of the urological observations : proteinuria, hematuria, leucocyturia, glycosuria and nitrituria
from sklearn.tree import DecisionTreeRegressor

def schisto_intensity (haem_para, u_schisto):
    dtr = DecisionTreeRegressor(max_depth=4, min_impurity_decrease=5, max_leaf_nodes=10)
    haem_para = df[['haematuria','glycosuria','proteinuria','leukocyturia']] # these are other morbidities associated with schistosomiasis
    u_schisto = df[['sheggcnt']]

    for i in haem_para:
        haem_para = haem_para.reshape(-1,1)
        print(haem_para.corr(u_schisto))

    # importing the decision tree model
    model = dtr.fit(haem_para, u_schisto)
    # haem_para
    pred_schist = dtr.predict([[3,3,3,0]]) # note that the double angular brakets are required for the four predictors to predict new schisto values
    for i in haem_para:
        print(i)
    return pred_schist

if __name__ == '__main__':
    print(schisto_intensity(haem_para, u_schisto))
    print(model.score(haem_para, u_schisto))
    print(model.feature_importances_)
    print(model.predict([[3,3,3,0]]))

NameError: name 'haem_para' is not defined

In [ ]:
# df['haematuria'].corr(df['sheggcnt']) #0.348
# df['glycosuria'].corr(df['sheggcnt']) #has 0.65 correlation coeficient with sheggcount
# df['proteinuria'].corr(df['sheggcnt']) #0.442
# df['leukocyturia'].corr(df['sheggcnt']) #0.150
# df[[['sheggcnt']]].corr(df[['haematuria','glycosuria','proteinuria','leukocyturia']])
df[['sheggcnt']].corr(df[['haematuria','glycosuria','proteinuria','leukocyturia']])

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

Prediction using Support Vector Models : Regressor and Classifier

In [ ]:
# using decision tree to make sense out of the urological observations : proteinuria, hematuria, leucocyturia, glycosuria and nitrituria
from sklearn.svm import SVR
from sklearn.svm import SVC

SVR = SVR(kernel='rbf')

def schisto_intensity (haem_para, u_schisto):
    # dtr = DecisionTreeRegressor(max_depth=4, min_impurity_decrease=5, max_leaf_nodes=10)
    haem_para = df[['haematuria','glycosuria','proteinuria','leukocyturia']].values # these are other morbidities associated with schistosomiasis
    haem_para.reshape(-1,1)
    u_schisto = df[['sheggcnt']].values

    # importing the decision tree model
    svr_model = SVR.fit(haem_para, u_schisto)
    # model = dtr.fit(haem_para, u_schisto)
    # haem_para
    pred_schist = svr_model.predict([[3,3,3,0]]) # note that the double angular brakets are required for the four predictors to predict new schisto values
    return pred_schist

if __name__ == '__main__':
    print(schisto_intensity(haem_para, u_schisto))
    print(model.score(haem_para, u_schisto))
    print(model.feature_importances_)
    print(model.predict([[3,3,3,0]]))

#

[4.06875845]
0.8998202860303031
[0.02818397 0.94212305 0.02286759 0.00682539]
[2263.]


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
# using decision tree to make sense out of the urological observations : proteinuria, hematuria, leucocyturia, glycosuria and nitrituria
from sklearn.tree import DecisionTreeClassifier as dtc
from sklearn.tree import DecisionTreeRegressor as dtr
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler
from sklearn.utils import shuffle

def schisto_intensity (haem_para, u_schisto):
    # dtr = DecisionTreeRegressor(max_depth=4, min_impurity_decrease=5, max_leaf_nodes=10)
    haem_para = df[['haematuria','glycosuria','proteinuria','leukocyturia']].values # these are other morbidities associated with schistosomiasis
    haem_para.reshape(-1,1)
    u_schisto = df[['sheggcnt']].values

    # importing the decision tree model
    model = dtc.fit(haem_para, u_schisto)
    # haem_para
    pred_schist = dtc.predict([[3,3,3,0]]) # note that the double angular brakets are required for the four predictors to predict new schisto values
    return pred_schist

if __name__ == '__main__':
    print(schisto_intensity(haem_para, u_schisto))
    print(model.score(haem_para, u_schisto))
    print(model.feature_importances_)
    print(model.predict([[3,3,3,0]]))

[12]
0.8998202860303031
[0.02818397 0.94212305 0.02286759 0.00682539]
[2263.]


In [ ]:
# visualizing the the decision tree regression results( higher resolution)
from sklearn import tree
import graphviz
import pydot
import pydotplus
dot_data = tree.export_graphviz(model, out_file=None)
# dot_data

graph = pydotplus.graph_from_dot_data(dot_data)

graph.write_pdf("psac_korede.pdf")

In [ ]:
# This is the multiple linear regression still observing the relationship between these four predictors with schistosomiasis
# N.B that the schistosoma eggcount used here is not normalized
haem_para = df[['haematuria','glycosuria','proteinuria','leukocyturia']].values # these are other morbidities associated with schistosomiasis
haem_para.reshape(-1,1)
u_schisto = df[['sheggcnt']].values
u_schisto

x_train,x_test, y_train, y_test = train_test_split(haem_para, u_schisto, test_size=0.2, random_state=42)

from sklearn.linear_model import LinearRegression
lr = LinearRegression()

lr_model = lr.fit(x_train, y_train)

prediction = lr.predict(x_test)
prediction
# plt.scatter(x_test,y_test, color="red")

# Now to know the model accuracy in order to ascertain if its a good model

from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_test, prediction)
# computing the regression coeficient, mean squared error and the variance score.. N.B variance score 1 is perfect

print(lr.coef_)
print(mse)
print(r2_score(y_test, prediction))

[[21.17199234 11.98799001 10.35852615  9.46719824]]
215072.5244638541
0.05376341563705145


In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [ ]:
df_qual = pd.read_csv('/content/drive/MyDrive/koredepsac/psacqual (1).csv')
df_qual
# df_qual.dropna(inplace=True)
# df_qual.isnull().sum() # this counts the number of nodata present in the datasets
sex = df_qual.iloc[:,0].values
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
scaled_sex = le.fit_transform(sex)
scaled_sex # the sex of  the children have coded into 1s and 0s now usable for analysis.

# Now sing OneHotEncoder to code other features , this tells me that those qualitative data could also be coded into integers/float
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
# df_qual.reshape(-1,1)
# new_parentoccup = ohe.fit_transform(df_qual.iloc[:,7])
# new_parentoccup

In [3]:
prev = df_qual.Schistointensitylevel
def schisto_prevalence(prev):
    for i in df_qual.Schistointensitylevel:
        if i == negative:
            df_qual.Schistointensitylevel = 0
        elif i == moderate:
            df_qual.Schistointensitylevel = 1
        elif i == severe:
            df_qual.Schistointensitylevel = 2

    return df_qual.Schistointensitylevel

schisto_prevalence(negative)

NameError: name 'df_qual' is not defined

In [ ]:
from sklearn.preprocessing import MinMaxScaler
new_df_qual = df_qual.dropna
# df_train, df_test = train_test_split (new_df_qual,test_size=0.25, random_state=0)
mms = MinMaxScaler()
# sil = df_qual.Schistointensitylevel
# shint_ohe = ohe.fit_transform(sil)
# new_df_qual = pd.DataFrame(mms.fit_transform(df_qual))
# new_df_train = pd.DataFrame(mms.fit_transform(df_train), columns=df_train.columns)
# new_df_train = ohe.fit_transform(df_train)


In [ ]:
# comparing the exposure duration source of exposure to schistosomiasis and hematuria symptoms

dur_source = df_qual.iloc[:, 22:23].values
dur_source

nu_dur_source = ohe.fit_transform(dur_source)
nu_dur_source

<111x5 sparse matrix of type '<class 'numpy.float64'>'
	with 111 stored elements in Compressed Sparse Row format>

In [ ]:
# df.corr()